var dir_1664bd36a745a898ec6d2a8359b7e115 =
[
    [ "listeners", "dir_3c16dda534b74afc10ce5b4e114bcc7b.html", "dir_3c16dda534b74afc10ce5b4e114bcc7b" ],
    [ "alloc.h", "alloc_8h.html", "alloc_8h" ],
    [ "alloc_hooks.h", "alloc__hooks_8h.html", "alloc__hooks_8h" ],
    [ "base_types.h", "base__types_8h.html", "base__types_8h" ],
    [ "core_events.h", "core__events_8h.html", "core__events_8h" ],
    [ "cpu_usage.h", "cpu__usage_8h.html", "cpu__usage_8h" ],
    [ "duration_conversion.h", "duration__conversion_8h.html", "duration__conversion_8h" ],
    [ "event_id_provider.h", "event__id__provider_8h.html", "event__id__provider_8h" ],
    [ "event_macros.h", "event__macros_8h.html", "event__macros_8h" ],
    [ "event_macros_impl.h", "event__macros__impl_8h.html", "event__macros__impl_8h" ],
    [ "events.h", "events_8h.html", "events_8h" ],
    [ "feature_cached_string.h", "feature__cached__string_8h.html", "feature__cached__string_8h" ],
    [ "feature_callstack.h", "feature__callstack_8h.html", "feature__callstack_8h" ],
    [ "global_timeline.h", "global__timeline_8h.html", "global__timeline_8h" ],
    [ "init.h", "init_8h.html", "init_8h" ],
    [ "listeners.h", "listeners_8h.html", null ],
    [ "macros.h", "macros_8h.html", "macros_8h" ],
    [ "memory_usage.h", "memory__usage_8h.html", "memory__usage_8h" ],
    [ "mkcreflect.h", "mkcreflect_8h.html", "mkcreflect_8h" ],
    [ "monotonic_clock.h", "monotonic__clock_8h.html", "monotonic__clock_8h" ],
    [ "posix_mapped_tracepoint.h", "posix__mapped__tracepoint_8h.html", "posix__mapped__tracepoint_8h" ],
    [ "registry.h", "hawktracer_2registry_8h.html", "hawktracer_2registry_8h" ],
    [ "scoped_tracepoint.h", "scoped__tracepoint_8h.html", "scoped__tracepoint_8h" ],
    [ "scoped_tracepoint.hpp", "scoped__tracepoint_8hpp.html", [
      [ "ScopedTracepoint", "class_hawk_tracer_1_1_scoped_tracepoint.html", "class_hawk_tracer_1_1_scoped_tracepoint" ]
    ] ],
    [ "string_scoped_tracepoint.h", "string__scoped__tracepoint_8h.html", "string__scoped__tracepoint_8h" ],
    [ "system_info.h", "system__info_8h.html", "system__info_8h" ],
    [ "task_scheduler.h", "task__scheduler_8h.html", "task__scheduler_8h" ],
    [ "thread.h", "thread_8h.html", "thread_8h" ],
    [ "timeline.h", "timeline_8h.html", "timeline_8h" ],
    [ "timeline_listener.h", "timeline__listener_8h.html", "timeline__listener_8h" ]
];